[client]
showErrorDetails = false
showWarningOnDirectExecution = false

[server]
headless = true
port = 8501
maxUploadSize = 200
enableXsrfProtection = true

[logger]
level = "error"

[theme]
primaryColor = "#2d9e5f"
backgroundColor = "#f5f1e8"
secondaryBackgroundColor = "#f5f1e8"
textColor = "#333333"
font = "sans serif"
